// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCF26yOQX4OLCQUWDQzokZ35Y6-HFyQbv4',
    appId: '1:954142334279:web:79f26210e6fb5567414062',
    messagingSenderId: '954142334279',
    projectId: 'foodapplication-a2161',
    authDomain: 'foodapplication-a2161.firebaseapp.com',
    storageBucket: 'foodapplication-a2161.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1rxT-PH8pMArm34HEiqDAY2o7eAGkHFs',
    appId: '1:954142334279:android:129ffc741c38c731414062',
    messagingSenderId: '954142334279',
    projectId: 'foodapplication-a2161',
    storageBucket: 'foodapplication-a2161.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXe5puTwyEafV4YcPx45_waHMy1el3ZgQ',
    appId: '1:954142334279:ios:9e67dbfd7fbd2d16414062',
    messagingSenderId: '954142334279',
    projectId: 'foodapplication-a2161',
    storageBucket: 'foodapplication-a2161.firebasestorage.app',
    iosBundleId: 'com.example.loginSignup',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCXe5puTwyEafV4YcPx45_waHMy1el3ZgQ',
    appId: '1:954142334279:ios:9e67dbfd7fbd2d16414062',
    messagingSenderId: '954142334279',
    projectId: 'foodapplication-a2161',
    storageBucket: 'foodapplication-a2161.firebasestorage.app',
    iosBundleId: 'com.example.loginSignup',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCF26yOQX4OLCQUWDQzokZ35Y6-HFyQbv4',
    appId: '1:954142334279:web:481bc11bc40b1a57414062',
    messagingSenderId: '954142334279',
    projectId: 'foodapplication-a2161',
    authDomain: 'foodapplication-a2161.firebaseapp.com',
    storageBucket: 'foodapplication-a2161.firebasestorage.app',
  );
}
